### ISSUE TITLE
M1 mac无法打开题目信息

### ISSUE THREAD

**Issue by amcones** [starcatmeow/vjudge-helper#2]
可以正常登录，获取contests列表，但是点题目右下角就会有fetching problem description一段时间过后闪退，无法打开题目信息
在m1 mac mini和m1p mbp上情况相同

**Comment by starcatmeow** [comment]
最新的[release](https://github.com/starcatmeow/vjudge-helper/releases/tag/v0.2.3)应该修复这个问题了，在插件商城中更新即可。

**Comment by sky4178** [comment]
m2 mac无法打开部分信息

**Comment by starcatmeow** [comment]
> m2 mac无法打开部分信息

能更具体一点吗？我这边功能正常

**Comment by sky4178** [comment]
未挂梯子测试，也只能打开一部分。



---- 回复的原邮件 ----
| 发件人 | Dongruixuan ***@***.***> |
| 日期 | 2023年11月18日 01:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [starcatmeow/vjudge-helper] M1 mac无法打开题目信息 (Issue #2) |

m2 mac无法打开部分信息

能更具体一点吗？我这边功能正常

**Comment by sky4178** [comment]
感想关注到我的问题。



---- 回复的原邮件 ----
| 发件人 | Dongruixuan ***@***.***> |
| 日期 | 2023年11月18日 01:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [starcatmeow/vjudge-helper] M1 mac无法打开题目信息 (Issue #2) |

m2 mac无法打开部分信息

能更具体一点吗？我这边功能正常

**Comment by starcatmeow** [comment]
> 未挂梯子测试，也只能打开一部分。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Dongruixuan ***@***.***> | | 日期 | 2023年11月18日 01:09 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [starcatmeow/vjudge-helper] M1 mac无法打开题目信息 (Issue #2) | m2 mac无法打开部分信息 能更具体一点吗？我这边功能正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

能提供一个具体的题目编号吗？

**Comment by sky4178** [comment]
codeforces-1829F
Forever winter



---- 回复的原邮件 ----
| 发件人 | Dongruixuan ***@***.***> |
| 日期 | 2023年11月18日 01:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [starcatmeow/vjudge-helper] M1 mac无法打开题目信息 (Issue #2) |

未挂梯子测试，也只能打开一部分。
…
---- 回复的原邮件 ---- | 发件人 | Dongruixuan @.> | | 日期 | 2023年11月18日 01:09 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [starcatmeow/vjudge-helper] M1 mac无法打开题目信息 (Issue #2) | m2 mac无法打开部分信息 能更具体一点吗？我这边功能正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

能提供一个具体的题目编号吗？

**Comment by starcatmeow** [comment]
<img width="628" alt="Screenshot 2023-11-17 at 12 31 39 PM" src="https://github.com/starcatmeow/vjudge-helper/assets/19618963/0c7677a6-b7f5-430b-8b0a-0d06b87c17c7">
我在最新版本上测试，不存在问题，可以发送一下VS Code Output底栏中Extension Host的相关log吗？

**Comment by sky4178** [comment]
可以告诉怎么查看吗？



---- 回复的原邮件 ----
| 发件人 | Dongruixuan ***@***.***> |
| 日期 | 2023年11月18日 01:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [starcatmeow/vjudge-helper] M1 mac无法打开题目信息 (Issue #2) |

我在最新版本上测试，不存在问题，可以发送一下VS Code Output底栏中Extension Host的相关log吗？

**Comment by starcatmeow** [comment]
<img width="1247" alt="Screenshot 2023-11-17 at 12 45 07 PM" src="https://github.com/starcatmeow/vjudge-helper/assets/19618963/070c796b-b86f-4464-9c29-96afcb089823">

这样选择后，把与vjudge-helper相关的log发上来

**Comment by starcatmeow** [comment]
<img width="1247" alt="Screenshot 2023-11-17 at 12 45 07 PM" src="https://github.com/starcatmeow/vjudge-helper/assets/19618963/070c796b-b86f-4464-9c29-96afcb089823">

这样选择后，把与vjudge-helper相关的log发上来

**Comment by sky4178** [comment]
<img width="1470" alt="截屏2023-11-18 01 53 07" src="https://github.com/starcatmeow/vjudge-helper/assets/142413065/d668659c-7291-4a9f-8c96-e93dfc2078c5">

**Comment by sky4178** [comment]
邮件可能有点问题



---- 回复的原邮件 ----
| 发件人 | Dongruixuan ***@***.***> |
| 日期 | 2023年11月18日 01:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [starcatmeow/vjudge-helper] M1 mac无法打开题目信息 (Issue #2) |

这样选择后，把与vjudge-helper相关的log发上来

**Comment by starcatmeow** [comment]
可以再截一下developer tools里的console吗？

<img width="374" alt="Screenshot 2023-11-17 at 1 39 33 PM" src="https://github.com/starcatmeow/vjudge-helper/assets/19618963/d16d61c9-43d2-4f96-84c4-90702a889701">

点击toggle developer tools后，点到右边的console里，重新加载题目，然后把报错/警告信息截一下。

**Comment by sky4178** [comment]
<img width="1470" alt="截屏2023-11-18 03 07 27" src="https://github.com/starcatmeow/vjudge-helper/assets/142413065/33e0e596-d007-4142-9f65-1096952b7b8a">

**Comment by fire-mirror** [comment]
0.2.4版本没有提交题目的位置，另外，希望可以有获取新题单的功能

**Comment by starcatmeow** [comment]
> 0.2.4版本没有提交题目的位置，另外，希望可以有获取新题单的功能

刚发现是 VJudge 提交题目 API 有调整，现在新的0.2.5版本能正常提交题目了。获取题单的功能可能需要在未来做了，最近比较忙，如果方便的话，你也可以实现下然后提下 PR。

**Comment by fire-mirror** [comment]
thanks
&nbsp;


裴奋伟—03-辅导员申请
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dongruixuan ***@***.***&gt;; 
发送时间: 2024年5月19日(星期天) 下午3:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [starcatmeow/vjudge-helper] M1 mac无法打开题目信息 (Issue #2)














  
0.2.4版本没有提交题目的位置，另外，希望可以有获取新题单的功能
  
刚发现是 VJudge 提交题目 API 有调整，现在新的0.2.5版本能正常提交题目了。获取题单的功能可能需要在未来做了，最近比较忙，如果方便的话，你也可以实现下然后提下 PR。
