### ISSUE TITLE
Couldn't submit my code to Virtual Judge

### ISSUE THREAD

**Issue by AuraElicase** [starcatmeow/vjudge-helper#3]
When I using this extension to submit my code, vscode shows this message:
~~~
运行命令 vjudge-helper.submitCode 错误: Cannot convert undefined or null to object。这可能是由提交 vjudge-helper.submitCode 的扩展引起的。
~~~
I tried only open the code I need submit or select all my code and press the cloud buttom. it shows the message again.

**Comment by starcatmeow** [comment]
Try update the plugin to v0.2.4 in vscode marketplace. It changed the submit method to match the current version of VJudge submit API, should work fine now.

**Comment by SpecterLiZN** [comment]
But this problem reappeared on my computer, my plugin version is v0.2.8. 
`运行命令 vjudge-helper.submitCode 错误: Cannot convert undefined or null to object。这可能是由提交 vjudge-helper.submitCode 的扩展引起的。`
I tried only open the code file or select all my code and press the cloud button,just as the thread starter said,and this error appears again.
