### ISSUE TITLE
Missing JS resource for some type of statements

### ISSUE THREAD

**Issue by starcatmeow** [starcatmeow/vjudge-helper#5]
<img width="1470" alt="截屏2023-11-18 03 07 27" src="https://github.com/starcatmeow/vjudge-helper/assets/142413065/33e0e596-d007-4142-9f65-1096952b7b8a">

_Originally posted by @sky4178 in https://github.com/starcatmeow/vjudge-helper/issues/2#issuecomment-1816950095_

**Comment by starcatmeow** [comment]
@sky4178 能提供一下这个题目的原始编号吗，这个题目似乎使用了和以往不同的题面展示方式。

**Comment by sky4178** [comment]
我12点之后（下午）有时间，现在上课。



---- 回复的原邮件 ----
| 发件人 | Dongruixuan ***@***.***> |
| 日期 | 2023年11月18日 08:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [starcatmeow/vjudge-helper] Missing JS resource for some type of statements (Issue #5) |

@sky4178 能提供一下这个题目的原始编号吗，这个题目似乎使用了和以往不同的题面展示方式。

**Comment by sky4178** [comment]
上午的题为CF632A
下面是forever winter的结果



---- 回复的原邮件 ----
| 发件人 | Dongruixuan ***@***.***> |
| 日期 | 2023年11月18日 08:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [starcatmeow/vjudge-helper] Missing JS resource for some type of statements (Issue #5) |

@sky4178 能提供一下这个题目的原始编号吗，这个题目似乎使用了和以往不同的题面展示方式。

**Comment by starcatmeow** [comment]
不好意思，前段时间一直比较忙，我使用你的这两个题号在vjudge新建比赛，似乎无法复现该问题。
