### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by Anorexia16** [starcatmeow/vjudge-helper#6]
v0.2.5
左侧栏功能中的Login Now按钮没有反应
反复卸载重装了几次

命令中的vjudge-helper.login弹出：
❌
Command 'Vjudge:Login' resulted in an error
command 'vjudge-helper.login' not found
![屏幕截图 2024-05-21 193442](https://github.com/starcatmeow/vjudge-helper/assets/56213634/610c8fea-5a15-46b5-913a-31a4e3ab537e)

**Comment by Anorexia16** [comment]
退回v0.2.4之后问题解决了，vscode marketplace上 2.4的vsix好像比2.5大了很多，2.5版本更新遗漏了文件吗

**Comment by starcatmeow** [comment]
感谢提醒，可能是vsce版本过老，publish的时候没有把nodemodules正确包含进去。现在升级了，更新到最新的v0.2.7即可。
