### ISSUE TITLE
无法打开题目

### ISSUE THREAD

**Issue by floatbamboo** [starcatmeow/vjudge-helper#7]
打开题目会显示Fetching Problem Description，然后消失，但可以正常提交
<img width="343" alt="屏幕截图 2024-07-13 144807" src="https://github.com/user-attachments/assets/969e6bde-1b90-421e-a536-f33bc838eca2">

**Comment by Anorexia16** [comment]
+1

**Comment by starcatmeow** [comment]
VJudge侧API有变动，已在v0.2.8中修复，可以试试更新后是否正常

**Comment by floatbamboo** [comment]
已可以正常使用，感谢
