### ISSUE TITLE
无法提交题目

### ISSUE THREAD

**Issue by yunshujing** [starcatmeow/vjudge-helper#8]
显示“运行命令 vjudge-helper.submitCode 错误: Cannot convert undefined or null to object。这可能是由提交 vjudge-helper.submitCode 的扩展引起的。”
版本v0.2.8

**Comment by SpecterLiZN** [comment]
This problem also appeared on my computer , my plugin version is v0.2.8.  
`运行命令 vjudge-helper.submitCode 错误: Cannot convert undefined or null to object。这可能是由提交 vjudge-helper.submitCode 的扩展引起的。`  
I tried only open the code file or select all my code and press the cloud button,just as the thread starter said,and this error appears again.

**Comment by Tiancheng12345** [comment]
Me 2
